version: '2'

services:
  peoplemap:
    image: jslowack/peoplemap
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  app:
    image: jslowack/peoplemap-client
    ports:
      - 80:80
